### ISSUE TITLE
4.0.0-beta.12 throws a startsWith error when AUTH0_DOMAIN not set

### ISSUE THREAD

**Issue by robcaldecott** [auth0/nextjs-auth0#1849]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We have just upgraded from `4.0.0-beta.10` to `4.0.0-beta.12` and our `next build` inside a `docker` container is failing for **route handlers that call `getAccessToken`**.

We build our app in `docker` with no env vars set, so all the Auth0 variables will be missing. We then inject these into the container when it actually runs. Until now this has not been an issue.

But with `beta.12` the following route handler will cause `next build` to error:

```ts
import { auth0 } from "@/auth0/client";

export function async GET() {
  const session = await auth0.getAccessToken();
  ... 
}
```

This causes the following error:

```
Collecting page data  ..TypeError: Cannot read properties of undefined (reading 'startsWith')
    at new rv (.next/server/chunks/8423.js:1:49131)
    at new aR (.next/server/chunks/8423.js:1:95081)
    at 44684 (.next/server/app/api/customers/[id]/route.js:1:4294)
    at t (.next/server/webpack-runtime.js:1:142)
    at 84331 (.next/server/app/api/customers/[id]/route.js:1:1086)
    at t (.next/server/webpack-runtime.js:1:142)
    at t (.next/server/app/api/customers/[id]/route.js:1:4586)
    at <unknown> (.next/server/app/api/customers/[id]/route.js:1:4634)
    at t.X (.next/server/webpack-runtime.js:1:1270)
    at <unknown> (.next/server/app/api/customers/[id]/route.js:1:4599)
```

I have tied forcing the routes causing this to by dynamic like this:

```
export const dynamic = "force-dynamic";
```

But to no avail.

It appears that this happens if `AUTH0_DOMAIN` is not set at build time. However, if this is set to an **empty string** then it works. Any ideas how we can handle this? Could the auth0 code check for `undefined` to handle this?

### Reproduction

- Create a new Next.js app with the auth0 beta.
- Add a route handler that calls `getAccessToken`
- Run `next build` without setting `AUTH0_DOMAIN`

### nextjs-auth0 version

4.0.0-beta.12

### Next.js version

15.1

### Node.js version

20

**Comment by robcaldecott** [comment]
Note that wrapping `getAccessToken` in `try ... catch` does not help either. 😢 we still get the error during the build.

**Comment by guabu** [comment]
Hey @robcaldecott, this was a regression introduced in `4.0.0-beta.11`. Apologies for the inconvenience here, we'll get this resolved in the upcoming release.

For the time being, setting the `AUTH0_DOMAIN` environment variable as temporary workaround as you mentioned should ensure the build succeeds.

**Comment by guabu** [comment]
This should now be fixed in the latest release (`4.0.0-beta.13`). Thanks for reporting this!

**Comment by pavinduLakshan** [comment]
This bug is still reproducible with the latest version 4.5.1. Setting AUTH0_DOMAIN environment variable fixed the issue, as some one had mentioned above.
