### ISSUE TITLE
HTTP Error 431

### ISSUE THREAD

**Issue by bchurlinov** [auth0/nextjs-auth0#499]
**Description**

Hi,

I am getting a really strange error in one of the applications that I am using. I have another two applications working just fine using the same settings but I am getting HTTP ERROR 431 ( https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431 ) the same moment I click on the "login" button which then hits the "login" route.

I noticed that the same moment I hit the login route, under "Application -> Cookies" ( chrome ) I see 4 cookies are being created: appSession.0, appSession.1, appSession.2, appSession.3. Once I delete these everything works as normal but this keeps happening.

On the other application I am using, once I hit login, I can only see only appSession.0 and appSession.1. Not sure if this means something though.

The weird part is that this happens on Chrome but not on Mozilla, at least I tried it a few times on Mozilla.

**Environment**
"@auth0/nextjs-auth0": "1.5.0"
"next": "11.0.1"

**Comment by Widcket** [comment]
Hi @bchurlinov, thanks for raising this.
Seems like you have too much data on the user profile, causing Node to go over its header size limit. Check out https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md#2-how-can-i-reduce-the-cookie-size

**Comment by Widcket** [comment]
@bchurlinov seems like your issue has been solved, so I'll close this one for now. Please ping if you'd prefer to reopen.

**Comment by alexkiko** [comment]
hi @Widcket, i'm currently experiencing this exact same issue. (From the FAQ) Can you please provide a code example of how:

> to remove unused claims from the user profile
> set storeIDToken config to false

FWIW, setting the `-max-http-header-size` did not seem to solve the issue
