### ISSUE TITLE
Update to Next.js 12.1.6 breaks kitchen-sink-example

### ISSUE THREAD

**Issue by jl75** [auth0/nextjs-auth0#657]
### Description

After updating to Next.js 12.1.6, kitchen-sink-example fails to build with the following error on file pages/api/my/shows.ts:11:13:

Type error: Argument of type '(req: NextApiRequest, res: NextApiResponse<any>) => Promise<unknown>' is not assignable to parameter of type 'IApiRoute'.
  Type 'Promise<unknown>' is not assignable to type 'Promise<void>'.
    Type 'unknown' is not assignable to type 'void'.

   9 | 
  10 | const requireScope = (scope: string, apiRoute: NextApiHandler) =>
> 11 |   verifyJwt(async (req, res) => {
     |             ^
  12 |     const { claims } = (req as NextAuthenticatedApiRequest).identityContext
  13 |     if (
  14 |       !claims ||
info  - Checking validity of types .%

The error comes from NextJwtVerifier which is imported from @serverless-jwt/next (sandrinodimattia/serverless-jwt). I did not look further into NextJwTVerifier.

### Reproduction

Clone the kitchen-sink-example, update to Next.js 12.1.6, and build the example.

### Environment

The example was built using the latest version of nextjs-auth0 (1.7.0). Although not relevant, I'm building on MacOS 11.6.5 and/or GitHub Actions (ubuntu-latest).

**Comment by adamjmcgrath** [comment]
Thanks for raising this @jl75 - should be fixed by #659

**Comment by jl75** [comment]
I updated nextjs-auth0 to 1.8.0 and rebuilt the kitchen-sink-example. This still fails with the same error. All you have to do to reproduce the error is to clone the repository and execute npm run build:kitchen-sink

Could you please reopen this issue and investigate further?

**Comment by jl75** [comment]
Thank you and the team for your continued work on nextjs-auth0.

I have updated nextjs-auth0 to 1.8.0 and rebuilt my local kitchen-sink-example. This still fails with the same error. My local version has minor changes compared to version from the repository (only dev-dependencies, no code changes). Please note that when I clone the repository and execute `npm run build:kitchen-sink` the error is not detected.

In my local kitchen-sink-example, I have installed up-to-date versions of eslint (with plugins and configs). My linting settings follow official Next.js advisories. I believe some of this triggers the error.

When building the kitchen-sink-example from the repository, I get the following warning:
`warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config`

Also, when I run `npm outdated` on the nextjs-auth0 repository I get a huge list of outdated npm packages. This will make it hard (for me at least) to integrate with nextjs-auth0 going forward.

Could you please reopen this issue and investigate further? In the meantime, I will also look into this issue in detail. Thanks in advance.

**Comment by adamjmcgrath** [comment]
@jl75 - the kitchen-sink example is building correctly for me on master (and on [our CI](https://app.circleci.com/pipelines/github/auth0/nextjs-auth0/708/workflows/52be80f6-5e56-4923-a7fc-3b91a1e906a0/jobs/787/parallel-runs/0/steps/0-109))

Recommend you delete `examples/kitchen-sink-example/.next/` and try again (or failing that a clean repo)
